# -*- coding: utf-8 -*-
"""00_load_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNsIzrLY1gs2t-HE9cCnDSLy0Nq3bveE

# 00_load_data (Data đã được xử lý bằng SQL)

Dữ liệu sử dụng trong project này đã được:
- Làm sạch
- Chuẩn hoá
- Tổng hợp theo theo các tháng

toàn bộ bằng SQL trước khi đưa vào Python.

Notebook này chỉ thực hiện:
- Load dữ liệu đầu vào
- Kiểm tra cấu trúc dữ liệu
- Chuẩn bị dataframe dùng cho các notebook phân tích

B1: Import Thư viện
"""

import pandas as pd
import numpy as np

"""B2: Load data"""

from google.colab import drive
drive.mount('/content/drive')

path_lv2   = "/content/drive/MyDrive/python/Quick_Report/Data_by_Month/Sep/data_by_level2.csv"
path_items = "/content/drive/MyDrive/python/Quick_Report/Data_by_Month/Sep/data_by_item.csv"

df_source_lv2   = pd.read_csv(path_lv2)
df_source_items = pd.read_csv(path_items)

"""Lọc data theo tháng hiện tại"""

df_cur_items = df_source_items[df_source_items['year_month'] == '2024-09']

df_cur_lv2 = df_source_lv2[df_source_lv2['year_month'] == '2024-09']

"""Kiểm tra nhanh dữ liệu"""

df_cur_items.head()

df_cur_items.shape

df_cur_items.isna().sum()