# -*- coding: utf-8 -*-
"""charts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ioYMBBHKfn6BA2qaH47xDpuddK2J5poX

Hàm các chart dùng trong report

## Phần 1: Tổng quan

### Chart bar
"""

import matplotlib.pyplot as plt

def plot_gmv_ado_dual_chart(df):


    fig, axes = plt.subplots(1, 2, figsize=(14, 4), sharey=False)

    categories = ['Vehicle Essentials', 'Home & Technical Supplies']

    for ax, cat in zip(axes, categories):
        data = df[df['level1_kpi_category'] == cat].sort_values('year_month')

        # Bar chart - GMV
        ax.bar(data['year_month'], data['AdGMV_M'], width=0.5, alpha=0.8)
        ax.set_title(f"{cat} - GMV & ADO")
        ax.set_xlabel("Year-Month")
        ax.set_ylabel("GMV")

        # Line chart - ADO (secondary axis)
        ax2 = ax.twinx()
        ax2.plot(data['year_month'], data['ADO_M'],color='darkorange', marker='o')
        ax2.set_ylabel("ADO")

        # X label xoay cho dễ đọc
        ax.tick_params(axis='x', rotation=45)

    plt.tight_layout()
    plt.show()

"""### Phần 2"""

def plot_cat(df_cat,cat):
    import matplotlib.pyplot as plt

    df_cat_ado = df_cat.sort_values('diff_ado', ascending=True)
    df_cat_gmv = df_cat.sort_values('diff_gmv', ascending=True)

    fig, axes = plt.subplots(1, 2, figsize=(16, 5), dpi=120)

    # ===== ADO =====
    colors_cat = ['#2ca02c' if v > 0 else '#d62728' for v in df_cat_ado['diff_ado']]
    axes[0].barh(
        df_cat_ado['level2_kpi_category'],
        df_cat_ado['diff_ado'],
        color= colors_cat
    )
    axes[0].set_title(f'{cat} – ADO Diff', weight='bold')
    axes[0].axvline(0)

    for i, v in enumerate(df_cat_ado['diff_ado']):
        axes[0].text(
            v, i, f'{v:,.0f}',
            va='center',
            ha='left' if v > 0 else 'right',
            fontsize=9
        )

    # ===== GMV =====
    colors_tool = ['#2ca02c' if v > 0 else '#d62728' for v in df_cat_gmv['diff_gmv']]
    axes[1].barh(
        df_cat_gmv['level2_kpi_category'],
        df_cat_gmv['diff_gmv'],
        color=colors_tool
    )
    axes[1].set_title(f'{cat} – GMV Diff', weight='bold')
    axes[1].axvline(0)

    for i, v in enumerate(df_cat_gmv['diff_gmv']):
        axes[1].text(
            v, i, f'{v:,.0f}',
            va='center',
            ha='left' if v > 0 else 'right',
            fontsize=9
        )
    plt.tight_layout()
    plt.show()

"""## Phần 3: Chất lượng tăng trưởng"""

#hàm vẽ chart heatmap
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def plot_heatmap_share(df,lv1):

# pivot
  heatmap_ado_df = (
            df[df['level1_kpi_category'] == lv1]
            .pivot_table(
               index = 'level2_kpi_category',
               columns = 'year_month',
               values = 'ado_share',
               aggfunc = 'sum'
              )
)

  heatmap_gmv_df = (
            df[df['level1_kpi_category'] == lv1]
            .pivot_table(
               index = 'level2_kpi_category',
               columns = 'year_month',
               values = 'gmv_share',
               aggfunc = 'sum'
              )
)

  fig, axes = plt.subplots(1, 2, figsize=(12, 6))

#----ADO----------

  sns.heatmap(
        heatmap_ado_df,
        cmap='Blues',
        annot=True,
        fmt='.1%',
        linewidths=0.5,
        ax=axes[0]
    )
  axes[0].set_title(f'{lv1} – ADO_share', weight='bold')
  axes[0].set_xlabel('Month')
  axes[0].set_ylabel('level2_category')

#----GMV----------

  sns.heatmap(
        heatmap_gmv_df,
        cmap='Blues',
        annot=True,
        fmt='.1%',
        linewidths=0.5,
        ax=axes[1]
    )
  axes[1].set_title(f'{lv1} – GMV_share', weight='bold')
  axes[1].set_xlabel('Month')

  plt.tight_layout()
  plt.show()