# -*- coding: utf-8 -*-
"""load_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CO4U7-DDwP-z8RRuweyYohm6sXhHP5WH
"""

import pandas as pd

def load_data(month="2024-09"):

    path_item = "/content/drive/MyDrive/Quick_Report/data_by_item.csv"
    path_lv2 = "/content/drive/MyDrive/Quick_Report/data_by_level2.csv"

    df_source_items = pd.read_csv(path_item)
    df_source_lv2 = pd.read_csv(path_lv2)

    df_cur_items = df_source_items[df_source_items["year_month"] == month]
    df_cur_lv2 = df_source_lv2[df_source_lv2["year_month"] == month]

    return df_cur_lv2, df_cur_items