# -*- coding: utf-8 -*-
"""metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1okFJqORBNkdbjXyjubAQdjOLC_-JE0OA
"""

# Format số
def format_num(val):
    """Hàm định dạng số: 1,000,000 hoặc +10%"""
    if pd.isna(val): return "0"
    return f"{val:+,.0f}"
# Format %
def format_pct(val):
    """Hàm định dạng phần trăm"""
    if pd.isna(val): return "0%"
    return f"{val:+.2%}"
# Format về lable
def growth_lable(val):
  if val > 0:
    return "tăng"
  elif val < 0:
    return "giảm"
  else:
    return "ổn định"

"""## Phần 1: Tổng quan

###Hàm tăng trưởng
"""

# Hàm tính tăng trưởng
def _growth(df_cat):

  ado_m = df_cat['ADO_M'].sum()
  ado_m1 = df_cat['ADO_M_1'].sum()
  gmv_m = df_cat['AdGMV_M'].sum()
  gmv_m1 = df_cat['AdGMV_M_1'].sum()

  return {
  'diff_ado' : ado_m - ado_m1,
  'diff_gmv' : gmv_m - gmv_m1,
  'grow_ado' : (ado_m - ado_m1) / ado_m1  if ado_m1 != 0 else 0,
  'grow_gmv':(gmv_m - gmv_m1) / gmv_m1  if gmv_m1 != 0 else 0,
}

# hàm tăng trưởng nhiều level
def growth_by_mul_level(df, level_cols):
    results = []

    base_col = ['ADO_M','ADO_M_1','AdGMV_M','AdGMV_M_1']

    for level_values, sub_df in df.groupby(level_cols):

        # tính growth cho từng group
        res = _growth(sub_df)

        # Giữ lại base col
        for c in base_col:
          res[c]=sub_df[c].sum()

        # gắn lại từng level vào kết quả
        for col, val in zip(level_cols, level_values):
            res[col] = val

        results.append(res)

    return pd.DataFrame(results)
# insight overview
def text_overview(df):

    diff_ado_overall = df['diff_ado'].sum()
    diff_gmv_overall = df['diff_gmv'].sum()
    grow_ado_overall = df['grow_ado'].sum()
    grow_gmv_overall = df['grow_gmv'].sum()

    # Tạo câu tổng quan
    overview_text = (
        f"\n\nNgành hàng **Vehicle Essentials & Home & Technical Supplies** "
        f"{growth_lable(diff_ado_overall)} {format_num(diff_ado_overall)} về ADO "
        f"({format_pct(grow_ado_overall)} MoM) và "
        f"{growth_lable(diff_gmv_overall)} {format_num(diff_gmv_overall)} về GMV "
        f"({format_pct(grow_gmv_overall)} MoM)."
    )

    # Tạo bullet từng Level 1
    texts_l1 = df.apply(
        lambda row: (
            f"**{row['level1_kpi_category']}**: "
            f"ADO {growth_lable(row['diff_ado'])} {format_num(row['diff_ado'])} "
            f"({format_pct(row['grow_ado'])} MoM), "
            f"GMV {growth_lable(row['diff_gmv'])} {format_num(row['diff_gmv'])} "
            f"({format_pct(row['grow_gmv'])} MoM)"
        ),
        axis=1
    )

    # Gộp tất cả lại
    final_text = (
        overview_text
        + "\n\n**Trong đó:**\n"
        + "\n".join(f"- {t}" for t in texts_l1)
    )
    return final_text
"""### Hàm keywords"""

noise_phrases = [
    # Marketing / bán hàng
    'sale off',
    'bán chạy',
    'thanh lý',
    'chính hãng',
    'giá rẻ',
    'cao cấp',
    'hỏa tốc','bảo hành'

    # Thuộc tính / mô tả
    'đa năng',
    'kim loại',
    'chi tiết',
    'khổ rộng',
    'dạng sóng',
    'lấy ánh sáng',
    'hai đầu',
    'dễ thương',
    'đáng yêu',
    'ánh sáng',
    'tự động',

    # Trạng thái / phạm vi
    'ngẫu nhiên',
    'tất cả',
    'bao gồm',
    'hàng loại 1',

    # Thương hiệu / sàn / địa danh
    'shopee',
    'shopee mall',
    'made in',
    'sài gòn',
    'hà nội',
    'ib shop','gù salaya'

    # Năm
    '2017', '2018', '2019',
    '2020', '2021', '2022',
    '2023', '2024', '2025'
]

noise_words = {
    # Đơn vị đo lường & thông số kỹ thuật
    'v', 'w', 'mah', 'ah', 'mm', 'cm', 'm', 'kg', 'g',
    'lít', 'ml', 'inch', 'size',
    '12v', '24v', '220v', '60w', '100w', '120w',

    # Hình thức đóng gói & số lượng
    'cái', 'chiếc', 'viên', 'hộp', 'thùng', 'gói',
    'cặp', 'đôi', 'set', 'lố', 'bịch', 'cuộn',
    'mét', 'tấm', 'miếng', 'sợi',
    'que', 'cây', 'chai', 'lọ', 'tuýp', 'bình','sỉ','lẻ','viền',
    # Vị trí & hướng
    'trước', 'sau', 'trái', 'phải',
    'trên', 'dưới', 'trong', 'ngoài',
    'giữa', 'bên', 'ngang', 'dọc',
    'đứng', 'nằm', 'gầm', 'hậu',

    # Hành động / mục đích
    'dành', 'cho', 'của', 'lắp', 'độ', 'chế',
    'thay', 'thế', 'sửa', 'chữa',
    'làm', 'tẩy', 'rửa', 'xịt', 'bôi',
    'trơn', 'đánh', 'bóng', 'dán', 'ốp',
    'che', 'đựng', 'treo', 'móc', 'giữ', 'nối', 'nhận','cách','ghi','miễn',

    # Tính chất chung
    'chuyên', 'dụng', 'mini', 'nhỏ', 'lớn', 'to',
    'zin', 'xịn', 'nhập', 'khẩu', 'nội', 'địa',
    'loại', 'tốt', 'dày', 'mọi','qsmotor',

    # Màu sắc
    'đen', 'trắng', 'đỏ', 'xanh', 'vàng',
    'bạc', 'tím', 'hồng', 'cam',
    'nâu', 'xám', 'màu', 'trong', 'suốt',

    # Marketing
    'sale', 'off', 'hot', 'new',
    'mới', 'giảm', 'giá', 'rẻ',
    'siêu', 'free', 'freeship',
    'tặng', 'kèm', 'top', 'best', 'trend',

    # Khác
    'phụ', 'kiện', 'linh', 'đồ', 'nghề', 'cụ',
    'thiết', 'bị', 'hơi', 'nước', 'khí', 'nén',
    'nhà', 'cửa', 'gia', 'đình',
    'full', 'nhiều', 'mẫu', 'đủ'
}

import re
import pandas as pd
import unicodedata

def clean_and_shorten(name, num_keywords=5):
    if pd.isna(name):
        return ''
    # 1. remove keycap emoji
    name = re.sub(r'[\d]\ufe0f?\u20e3', ' ', name)

    # 2. remove emoji khác
    name = re.sub(r'[\U0001F300-\U0001FAFF]', ' ', name)

    # 3. Normalize unicode nhưng KHÔNG encode ascii
    name = unicodedata.normalize('NFKC', name)

    # 4. Lowercase
    name = name.lower()

    # 5. Bỏ nội dung trong ngoặc
    name = re.sub(r'[\(\[\{].*?[\)\]\}]', ' ', name)

    # 6. Remove phrase trước (sale off, chính hãng...)
    for phrase in noise_phrases:
        name = re.sub(rf'\b{re.escape(phrase)}\b', ' ', name)

    # 7. Replace underscore bằng space
    name = name.replace('_', ' ')

    # 8. Remove emoji & ký tự đặc biệt (GIỮ tiếng Việt)
    name = re.sub(r'[^\w\sàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]', ' ', name)

    # 9. Split & remove noise word (1 từ)
    words = name.split()
    keywords = [w for w in words if w not in noise_words]

    # 10. Remove duplicate – giữ thứ tự
    seen = set()
    unique_keywords = []
    for w in keywords:
        if w not in seen:
            seen.add(w)
            unique_keywords.append(w)

    return ' '.join(unique_keywords[:num_keywords])

"""## Phần 2: Phân tích động lực tăng trưởng

### Cat tăng
"""

# Hàm cat đóng góp nhiều nhất
def highest_contrib(df, metric):

    if metric == 'ado':
        contrib_col = 'contrib_ado'
        diff_col = 'diff_ado'
    elif metric == 'gmv':
        contrib_col = 'contrib_gmv'
        diff_col = 'diff_gmv'
    else:
        raise ValueError("Invalid metric. Must be 'ado' or 'gmv'.")

    result = []

    for lvl1, sub_df in df.groupby('level1_kpi_category'):

        # Tổng toàn bộ
        total_contrib = sub_df[contrib_col].sum()
        total_diff = sub_df[diff_col].sum()

        # Top 3
        top3 = (
            sub_df
            .sort_values(contrib_col, ascending=False)
            .head(3)
            [['level1_kpi_category','level2_kpi_category', diff_col, contrib_col]]
        )

        # Tổng top 3
        top3_contrib = top3[contrib_col].sum()
        top3_diff = top3[diff_col].sum()

        # Other = total - top3
        others_row = pd.DataFrame([{
            'level1_kpi_category': lvl1,
            'level2_kpi_category': 'Others',
            diff_col: total_diff - top3_diff,
            contrib_col: total_contrib - top3_contrib
        }])

        result.append(pd.concat([top3, others_row], ignore_index=True))

    return pd.concat(result, ignore_index=True)
# Hàm top items 
def top3_items (df,metric):
  if metric == 'ado':
        diff_col = 'diff_ado'

  elif metric == 'gmv':
        diff_col = 'diff_gmv'
  else:
        raise ValueError("Invalid metric. Must be 'ado' or 'gmv'.")

  result= (
                df.sort_values(by =['level1_kpi_category',diff_col], ascending=[True,False])
                .groupby(['level2_kpi_category'])
                .head(3)
  )
  #result[contrib_col] = result[contrib_col].apply(format_pct)
  result = result [['level1_kpi_category','level2_kpi_category', 'keywords', diff_col]]

  return  result
# Hàm tăng trưởng âm
def top3_items_low (df,metric):
  if metric == 'ado':
        
        diff_col = 'diff_ado'
        col_M = 'ADO_M'
        col_M_1 = 'ADO_M_1'
  elif metric == 'gmv':
        
        diff_col = 'diff_gmv'
        col_M = 'AdGMV_M'
        col_M_1 = 'AdGMV_M_1'
  else:
        raise ValueError("Invalid metric. Must be 'ado' or 'gmv'.")

  result = df.sort_values([col_M_1], ascending= False).head(20)
  result= (
                df.sort_values(by =['level1_kpi_category',diff_col], ascending=[True,True])
                .groupby(['level2_kpi_category'])
                .head(3)
  )

  result = result [['level1_kpi_category','level2_kpi_category', 'keywords',col_M,col_M_1, diff_col]]

  return  result
# Text insight cat tăng
def insight_ado_gmv_from_items(
    contrib_ado_df,
    contrib_gmv_df,
    df_ado,
    df_gmv,
    lvl1
):

    # Lọc orthers
    sub_contrib_ado = contrib_ado_df.loc[
    (contrib_ado_df['level1_kpi_category'] == lvl1) &
    (contrib_ado_df['level2_kpi_category'] != 'Others'),
    ['level1_kpi_category','level2_kpi_category', 'diff_ado', 'contrib_ado']].copy()

    sub_contrib_gmv = contrib_gmv_df.loc[
    (contrib_gmv_df['level1_kpi_category'] == lvl1) &
    (contrib_gmv_df['level2_kpi_category'] != 'Others'),
    ['level1_kpi_category','level2_kpi_category', 'diff_gmv', 'contrib_gmv']].copy()

    # Lọc level 1 trong bảng items
    sub_ado = df_ado[df_ado['level1_kpi_category'] == lvl1].copy()
    sub_gmv = df_gmv[df_gmv['level1_kpi_category'] == lvl1].copy()

    lines = []
    lines.append(f"**Về {lvl1}**")

    # ================= ADO ================

    ado_names = ', '.join(sub_contrib_ado['level2_kpi_category'])
    ado_contrib = sub_contrib_ado['contrib_ado'].sum()

    lines.append(
        f"- **ADO**: Tăng trưởng chủ yếu đến từ các ngành hàng "
        f" **{ado_names}**, đóng góp {ado_contrib:.1%} tổng mức tăng. Một số sản phẩm tiêu biểu như: \n \n"
    )

    for lvl2 in sub_ado['level2_kpi_category'].unique():

        items = (
            sub_ado[sub_ado['level2_kpi_category'] == lvl2]
            .sort_values('diff_ado', ascending=False)
            .head(3)
        )

        item_text = ", ".join(
            f"**{i['keywords']}** ({i['diff_ado']:+.2f} ADO)"
            for _, i in items.iterrows()
        )

        lines.append(f"  - **{lvl2}**: {item_text}")

    # ================= GMV =================

    gmv_names = ', '.join(sub_contrib_gmv['level2_kpi_category'])
    gmv_contrib = sub_contrib_gmv['contrib_gmv'].sum()

    lines.append(
        "\n"
        f"- **GMV**: Tăng trưởng chủ yếu đến từ nhóm "
        f"(**{gmv_names}**), đóng góp {gmv_contrib:.1%} tổng mức tăng. Một số sản phẩm tiêu biểu như:\n \n"
    )

    for lvl2 in sub_gmv['level2_kpi_category'].unique():
        items = (
            sub_gmv[sub_gmv['level2_kpi_category'] == lvl2]
            .sort_values('diff_gmv', ascending=False)
            .head(3)
        )

        item_text = ", ".join(
            f"**{i['keywords']}** ({i['diff_gmv']:+.2f} GMV)"
            for _, i in items.iterrows()
        )

        lines.append(f"  - **{lvl2}**: {item_text}")

    return "\n \n".join(lines)
# Hàm cat giảm
def insight_low_ado_gmv_items(
    contrib_ado_df,
    contrib_gmv_df,
    df_ado,
    df_gmv,
    lvl1
):
    # Lọc orthers
    sub_contrib_ado = contrib_ado_df.loc[
    (contrib_ado_df['level1_kpi_category'] == lvl1),
    ['level1_kpi_category','level2_kpi_category', 'diff_ado', 'contrib_ado']].copy()

    sub_contrib_gmv = contrib_gmv_df.loc[
    (contrib_gmv_df['level1_kpi_category'] == lvl1),
    ['level1_kpi_category','level2_kpi_category', 'diff_gmv', 'contrib_gmv']].copy()

    # Lọc level 1 trong bảng items
    sub_ado = df_ado[df_ado['level1_kpi_category'] == lvl1].copy()
    sub_gmv = df_gmv[df_gmv['level1_kpi_category'] == lvl1].copy()

    lines = []
    lines.append(f"**Về {lvl1}**")

    # ================= ADO ================

    ado_names = ', '.join( sub_contrib_ado['level2_kpi_category'])
    ado_contrib =  sub_contrib_ado['contrib_ado'].sum()

    lines.append(
        f"- **ADO**: Ngành hàng tăng trưởng chậm/ giảm gồm: "
        f"**{ado_names}**, chiếm {ado_contrib:.1%} tổng mức biến động. Một số sản phẩm giảm ADO đáng chú ý như: \n \n"
    )

    for lvl2 in sub_ado['level2_kpi_category'].unique():

        items = (
            sub_ado[sub_ado['level2_kpi_category'] == lvl2]
            .sort_values('diff_ado', ascending=False)
            .head(3)
        )

        item_text = ", ".join(
            f"**{i['keywords']}** ({i['diff_ado']:.2f} ADO)"
            for _, i in items.iterrows()
        )

        lines.append(f"  - **{lvl2}**: {item_text}.")

    # ================= GMV =================

    gmv_names = ', '.join(sub_contrib_gmv['level2_kpi_category'])
    gmv_contrib = sub_contrib_gmv['contrib_gmv'].sum()

    lines.append(
        "\n"
        f"- **GMV**: Ngành hàng tăng trưởng chậm/ giảm gồm: "
        f"(**{gmv_names}**), chiếm {gmv_contrib:.1%} tổng mức biến động. Một số sản phẩm giảm GMV đáng chú ý như: \n \n"
    )

    for lvl2 in sub_gmv['level2_kpi_category'].unique():
        items = (
            sub_gmv[sub_gmv['level2_kpi_category'] == lvl2]
            .sort_values('diff_gmv', ascending=False)
            .head(3)
        )

        item_text = ", ".join(
            f"**{i['keywords']}** ({i['diff_gmv']:.2f} GMV)"
            for _, i in items.iterrows()
        )

        lines.append(f"  - **{lvl2}**: {item_text}.")

    return "\n \n".join(lines)

"""## Phần 3: Chất lượng tăng trưởng"""
# Hàm phân vị cơ cấu và tăng trưởng cao
def quantile_share_diff (df,lv1):

  df_lv1 = df[df['level1_kpi_category']== lv1]

  lines = []
  lines.append(f"**{lv1}**")

#-------ADO

  q_share_ado = df_lv1['ado_share'].quantile(0.7)

  df_pos_ado = df_lv1[df_lv1['diff_ado']>0]
  if df_pos_ado.empty:
        return pd.DataFrame(columns= df_lv1.columns)
  q_diff_ado = df_pos_ado['diff_ado'].quantile(0.7)

  df_quantile_ado = df_lv1[
      (df_lv1['ado_share']>= q_share_ado)&
      (df_lv1['diff_ado']>= q_diff_ado)]

  # text
  quantile_ado_text = ", ".join(
        f" **{i['level2_kpi_category']}** (chiếm {i[('ado_share')]*100:.2f}% cơ cấu ADO "
        f"và tăng trưởng {i[('grow_ado')]*100:+.2f}% MoM )"
        for _, i in df_quantile_ado.iterrows()
    )
  lines.append(f"- **ADO**: ngành hàng có tỷ trọng cao và tăng trưởng tốt là {quantile_ado_text}.")
#-------GMV
  q_share_gmv = df_lv1['gmv_share'].quantile(0.7)

  df_pos_gmv = df_lv1[df_lv1['diff_gmv']>0]
  if df_pos_gmv.empty:
        return pd.DataFrame(columns= df_lv1.columns)
  q_diff_gmv = df_pos_gmv['diff_gmv'].quantile(0.7)

  df_quantile_gmv = df_lv1[
      (df_lv1['gmv_share']>= q_share_gmv)&
      (df_lv1['diff_gmv']>= q_diff_gmv)
  ]

  # text
  quantile_gmv_text = ", ".join(
        f"**{i['level2_kpi_category']}**(chiếm {i[('gmv_share')]*100:.2f}% cơ cấu GMV "
        f"và tăng trưởng {i[('grow_gmv')]*100:+.2f}% MoM )"
        for _, i in df_quantile_gmv.iterrows()
    )
  lines.append(f"- **GMV**: ngành hàng có tỷ trọng cao và tăng trưởng tốt là {quantile_gmv_text}.")
  return lines
# Hàm phân vị tăng trưởng cao, cơ cấu nhỏ:
def quantile_share_diff_2 (df,lv1):

  df_lv1 = df[df['level1_kpi_category']== lv1]

  lines = []
  lines.append(f"**{lv1}**")

#-------ADO

  q_share_ado = df_lv1['ado_share'].quantile(0.7)
  q_diff_ado = df_lv1['diff_ado'].quantile(0.7)

  df_quantile_ado = df_lv1[
      (df_lv1['ado_share'] < q_share_ado)&
      (df_lv1['diff_ado']>= q_diff_ado)]

  # text
  quantile_ado_text = ", ".join(
        f"**{i['level2_kpi_category']}** (chiếm {i[('ado_share')]*100:.2f}% cơ cấu ADO "
        f"và tăng trưởng {i[('grow_ado')]*100:+.2f}% MoM )"
        for _, i in df_quantile_ado.iterrows()
    )
  lines.append(f"- **ADO**: ngành hàng có tỷ trọng nhỏ nhưng tăng trưởng tốt là {quantile_ado_text}.")
#-------GMV
  q_share_gmv = df_lv1['gmv_share'].quantile(0.7)
  q_diff_gmv = df_lv1['diff_gmv'].quantile(0.7)

  df_quantile_gmv = df_lv1[
      (df_lv1['gmv_share']< q_share_gmv)&
      (df_lv1['diff_gmv']>= q_diff_gmv)
  ]

  # text
  quantile_gmv_text = ", ".join(
        f"**{i['level2_kpi_category']}** (chiếm {i[('gmv_share')]*100:.2f}% cơ cấu GMV "
        f"và tăng trưởng {i[('grow_gmv')]*100:+.2f}% MoM )"
        for _, i in df_quantile_gmv.iterrows()
    )
  lines.append(f"- **GMV**: ngành hàng có tỷ trọng nhỏ nhưng tăng trưởng tốt là {quantile_gmv_text}.")
  return lines
# Hàm phân vị tăng trưởng cao, tỷ trọng nhỏ:
def quantile_share_diff_3 (df,lv1):

  df_lv1 = df[df['level1_kpi_category']== lv1]

  lines = []
  lines.append(f"**{lv1}**")

#-------ADO

  q_share_ado = df_lv1['ado_share'].quantile(0.7)
  q_diff_ado = df_lv1['diff_ado'].quantile(0.7)

  df_quantile_ado = df_lv1[
      (df_lv1['ado_share'] >= q_share_ado)&
      (df_lv1['diff_ado']< q_diff_ado)]

  # text
  quantile_ado_text = ", ".join(
        f"**{i['level2_kpi_category']}** (chiếm {i[('ado_share')]*100:.2f}% cơ cấu ADO "
        f"nhưng {i[('grow_ado')]*100:+.2f}% MoM )"
        for _, i in df_quantile_ado.iterrows()
    )
  lines.append(f"- **ADO**: ngành hàng có tỷ trọng cao nhưng ghi nhận suy giảm MoM là {quantile_ado_text}.")
#-------GMV
  q_share_gmv = df_lv1['gmv_share'].quantile(0.7)
  q_diff_gmv = df_lv1['diff_gmv'].quantile(0.7)

  df_quantile_gmv = df_lv1[
      (df_lv1['gmv_share']>=q_share_gmv)&
      (df_lv1['diff_gmv']< q_diff_gmv)
  ]

  # text
  quantile_gmv_text = ", ".join(
        f"**{i['level2_kpi_category']}** (chiếm {i[('gmv_share')]*100:.2f}% cơ cấu GMV "
        f"nhưng {i[('grow_gmv')]*100:+.2f}% MoM )"
        for _, i in df_quantile_gmv.iterrows()
    )
  lines.append(f"- **GMV**: ngành hàng có tỷ trọng cao nhưng ghi nhận suy giảm MoM là {quantile_gmv_text}.")
  return lines

    
"""## Phần 4: Xu hướng ngành hàng"""
# Hàm xu hướng tăng:
def trend_grow(df,lv1):
  lines =[]
  df_cat = df[df['level1_kpi_category']==lv1]
  lines.append(f"**{lv1}** \n\n")
  #----------ADO
  # Tạo pivot
  df_month_ado = (df_cat
                  .pivot_table(
                      index = 'level2_kpi_category',
                      columns = 'year_month',
                      values = 'diff_ado',
                      aggfunc = 'sum'
                  ))
  df_month_gmv = (df_cat
                  .pivot_table(
                      index = 'level2_kpi_category',
                      columns = 'year_month',
                      values = 'diff_gmv',
                      aggfunc = 'sum'
                  ))
  # Text
  ado_text =[]
  for lv2, row in df_month_ado.iterrows():
    if not (row.dropna()>0).all():
      continue
    note = [
        f"T{int(m.split('-')[1])} {row[m]:+.2f} ADO"
        for m in row.index
    ]
    ado_text.append(f"**{lv2}** ({', '.join(note)})")
  if ado_text:
    lines.append(
    f" - **ADO**: Ngành hàng có xu hướng tăng "
    f'{", ".join(ado_text)}.'
    )
  else:
    lines.append(
    f"**ADO**: Không có ngành hàng nào có xu hướng tăng."
    )
  #----------GMV
  gmv_text = []
  for lv2,row in df_month_gmv.iterrows():
    if not (row.dropna() >0).all():
      continue
    note_gmv = [
        f"T{int(m.split('-')[1])} {row[m]:+.2f} GMV"
        for m in row.index
    ]
    gmv_text.append(f"**{lv2}** ({', '.join(note_gmv)})")
  if gmv_text:
            lines.append(
            f" - **GMV**: Ngành hàng có xu hướng tăng "
            f'{", ".join(gmv_text)}.'
            )
  else:
            lines.append(
            f"**GMV**: Không có ngành hàng nào có xu hướng tăng."
            )
  return lines
# Hàm xu hướng giảm
def trend_down(df,lv1):
  lines = []
  df_cat = df[df['level1_kpi_category']==lv1]
  lines.append(f'**{lv1}** \n\n')

  #ADO
  df_month_ado = (df_cat
                  .pivot_table(
                      index ='level2_kpi_category',
                      columns = 'year_month',
                      values = 'diff_ado',
                      aggfunc='sum'
                  ))
  ado_text =[]
  for lv2,row in df_month_ado.iterrows():
    if not (row.dropna()<0).all():
      continue
    note = [
        f'T{int(m.split('-')[1])} {row[m]:+.2f} ADO'
        for m in row.index # lấy cột trong bảng pivot là các tháng
    ]
    ado_text.append(f"**{lv2}** ({', '.join(note)})")
  if ado_text:
    lines.append(
    f" - **ADO**: Ngành hàng có xu hướng giảm "
    f"{', '.join(ado_text)}.\n\n"
    )
  else:
    lines.append(
        f" - **ADO**: Không có ngành hàng nào có xu hướng giảm.\n\n"
    )
  # GMV
  df_month_gmv = (df_cat
                  .pivot_table(
                      index = 'level2_kpi_category',
                      columns= 'year_month',
                      values = 'diff_gmv',
                      aggfunc = 'sum'
                  ))
  gmv_text =[]
  for lv2, row in df_month_gmv.iterrows():
      if not (row.dropna()<0).all():
       continue
      note_gmv = [
          f'T{int(m.split("-")[1])} {row[m]:+.2f} GMV'
          for m in row.index
      ]
      gmv_text.append(f"**{lv2}** ({', '.join(note_gmv)})")

  #code
  if gmv_text:
    lines.append(
        f" - **GMV**: Ngành hàng có xu hướng giảm "
        f"{', '.join(gmv_text)}.\n\n "
    )
  else:
    lines.append(
         f" - **GMV**: Không có ngành hàng nào có xu hướng giảm. "
    )
  return lines

"""## Phần 5: Xu hướng sản phẩm"""

### Hàm lọc bớt items diff<0
def items_keep (df,col):

  if col =='ado':
     col = 'ADO_M'
     col_M_1 = 'ADO_M_1'
     min_val = 0.05

  elif col =='gmv':
    col = 'AdGMV_M'
    col_M_1 = 'AdGMV_M_1'
    min_val = 1
  else:
    raise ValueError('must be ado or gmv')

 # lọc min
  df= df[df[col] > min_val].copy()

 # tính quantile và diff
  q_items = df[col].quantile(0.3)

  df['diff'] = df[col] - df[col_M_1]

  items_list = df[
      (df[col] >= q_items)
      |
      (df['diff'] <= 0)
  ]['keywords'].unique()

  #df_items = df.loc[df['keywords'].isin(items_list)].copy()

  return items_list
# Hàm total share
def total_share_items (df,col):
  if col == 'ado':
     col = 'ADO_M'
     col_m1 = 'ADO_M_1'
     col_share = 'share_ado'
  elif col == 'gmv':
       col = 'AdGMV_M'
       col_m1 = 'AdGMV_M_1'
       col_share = 'share_gmv'
  else:
    raise ValueError('metric must be ado or gmv')

  df = df.copy()
  df['total'] = (df
                 .groupby(['year_month','level2_kpi_category'])[col]
                 .transform('sum')
                )
  df[col_share] = df[col]/df['total']
  return df
# Hàm lọc items có xu hướng giảm:
def items_trend_down (df_items_diff,df_items_share,metric):

  if metric =='ado':
    diff_col = 'diff_ado'
    share_col = 'share_ado'
  elif metric =='gmv':
    diff_col = 'diff_gmv'
    share_col = 'share_gmv'
  else:
    raise ValueError('metric must be ado or gmv')

  # bảng pivot diff theo tháng
  pivot_grow = (df_items_diff
                .pivot_table(
                    index = 'keywords',
                    columns='year_month',
                    values = diff_col,
                    aggfunc='sum'
                )
                .sort_index(axis=1)
  )

  month_cols = pivot_grow.columns[1:].tolist()
  pivot_grow = (pivot_grow[month_cols].reset_index())

  # bảng pivot share theo tháng
  pivot_share  = (df_items_share
                .pivot_table(
                    index = ['level1_kpi_category','level2_kpi_category','keywords'],
                    columns='year_month',
                    values = share_col,
                    aggfunc='sum'
                )
  )

  #Lấy cột max_share
  share_base_df = (
        pivot_share
        .iloc[:, -3:]
        .max(axis=1)
        .rename('share_max_3m')
        .reset_index()
    )
  # Gộp hai bảng lại
  share_diff_df =  pivot_grow.merge(
                    share_base_df,
                    on ='keywords',
                    how='inner'
  )
  month_cols = [
        c for c in share_diff_df.columns
        if c not in ['keywords', 'level2_kpi_category', 'share_max_3m','level1_kpi_category']
    ]

  # Tính decline
  share_diff_df= share_diff_df.assign(
      decline_score = share_diff_df[month_cols].abs().sum(axis=1)
  )

  # Tính quantile
  q_share = share_diff_df['share_max_3m'].quantile(0.7)
  q_decline = share_diff_df['decline_score'].quantile(0.7)

  # lọc qua các điều kiện
  df_keep = share_diff_df[
      (share_diff_df['share_max_3m']>q_share) &
      (share_diff_df[month_cols]<0).all(axis=1) &
      (share_diff_df['decline_score']>q_decline)
  ]

  result = (df_keep
            .sort_values(['level2_kpi_category','decline_score'],ascending=[True,False])
            .groupby('level2_kpi_category')
            .head(5)
  )

  return result[
    ['level1_kpi_category','level2_kpi_category','keywords', 'share_max_3m', 'decline_score']
      ]
# Hàm lọc bớt items diff>0 và items_list
def items_keep_grow (df,col):

  if col =='ado':
     col = 'ADO_M'
     col_M_1 = 'ADO_M_1'
     min_val = 0.05

  elif col =='gmv':
    col = 'AdGMV_M'
    col_M_1 = 'AdGMV_M_1'
    min_val = 1
  else:
    raise ValueError('must be ado or gmv')

 # lọc min
  df= df[df[col] > min_val].copy()

 # tính quantile và diff
  q_items = df[col].quantile(0.3)

  df['diff'] = df[col] - df[col_M_1]

  items_list = df[
      (df[col] >= q_items)
      |
      (df['diff'] >= 0)
  ]['keywords'].unique()

  #df_items = df.loc[df['keywords'].isin(items_list)].copy()

  return items_list
# Hàm lọc items có xu hướng tăng:
def items_trend_grow (df_items_diff,df_items_share,metric):
  if metric =='ado':
    diff_col = 'diff_ado'
    share_col = 'share_ado'
  elif metric =='gmv':
    diff_col = 'diff_gmv'
    share_col = 'share_gmv'
  else:
    raise ValueError('metric must be ado or gmv')
  # bảng pivot diff theo tháng
  pivot_diff = (df_items_diff
                .pivot_table(
                    index = 'keywords',
                    columns='year_month',
                    values = diff_col,
                    aggfunc='sum'
                )
  )
  month_cols = pivot_diff.columns[1:].tolist()
  pivot_diff = (pivot_diff[month_cols].reset_index())

  # bảng pivot share theo tháng
  pivot_share  = (df_items_share
                .pivot_table(
                    index = ['keywords','level2_kpi_category','level1_kpi_category'],
                    columns='year_month',
                    values = share_col,
                    aggfunc='sum'
                )
  )

  #Lấy cột max_share
  share_base_df = (
                   pivot_share.iloc[:,-3:].max(axis=1)
                   .rename('share_max_3m')
                   .reset_index()
                  )

  # Gộp hai bảng lại
  share_diff_df =  pivot_diff.merge(
                    share_base_df,
                    on ='keywords',
                    how='inner'
  )
  month_cols=[
        c for c in share_diff_df.columns
        if c not in ['keywords','level2_kpi_category','share_max_3m','level1_kpi_category']
  ]

  # Tính increase
  share_diff_df= share_diff_df.assign(
      increase_score = share_diff_df[month_cols].abs().sum(axis=1)
  )

  # Tính quantile
  q_share = share_diff_df['share_max_3m'].quantile(0.7)
  q_increase = share_diff_df['increase_score'].quantile(0.7)

  # lọc qua các điều kiện
  df_keep = share_diff_df[
      (share_diff_df['share_max_3m']>q_share) &
      (share_diff_df[month_cols]>0).all(axis=1) &
      (share_diff_df['increase_score']>q_increase)
  ]

  result = (df_keep
            .sort_values(['level2_kpi_category','increase_score'],ascending=[True,False])
            .groupby('level2_kpi_category')
            .head(5)
  )
  return result[
    ['level1_kpi_category','level2_kpi_category','keywords', 'share_max_3m', 'increase_score']
]
## tableview grow
def table_view_grow (df):
  df_table = (
    df
    .assign(
        product_with_diff=lambda x:
        x['keywords'] + " (" + x['increase_score'].apply(format_num) + ")"
    )
    .groupby(['level1_kpi_category','level2_kpi_category'])['product_with_diff']
    .apply(lambda x: ", ".join(x))
    .reset_index()
    .sort_values(['level1_kpi_category','level2_kpi_category'],ascending=[True,True])
    )

  df_table.columns = ['Level 1','Level 2', 'Sản phẩm tiêu biểu| ΔADO lũy kế']

  # format bảng
  result = (
    df_table
    .style
    .set_properties(**{
        'white-space': 'pre-wrap',
        'text-align': 'left',
        'vertical-align': 'top',
        'border': '1px solid #ccc'
    })
    .set_table_styles([
        {'selector': 'th', 'props': [
            ('border', '1px solid #ccc'),
            ('background-color', '#f2f2f2'),
            ('font-weight', 'bold'),
            ('text-align', 'center')
        ]},
        {'selector': 'td', 'props': [
            ('border', '1px solid #ccc'),
            ('padding', '8px')
        ]}
    ])
    )
  return result
## Tableview down
def table_view_down (df):
  df_table = (
    df
    .assign(
        product_with_diff=lambda x:
        x.apply(
        lambda row: f"{row['keywords']} (-{abs(row['decline_score']):,.0f})",
        axis=1
    )
    )
    .groupby(['level1_kpi_category','level2_kpi_category'])['product_with_diff']
    .apply(lambda x: ", ".join(x))
    .reset_index()
    .sort_values(by=['level1_kpi_category','level2_kpi_category'],ascending=[True, True])
    )

  df_table.columns = ['Level 1','Level 2', 'Sản phẩm tiêu biểu| ΔADO lũy kế']

  # format bảng
  result = (
    df_table
    .style
    .set_properties(**{
        'white-space': 'pre-wrap',
        'text-align': 'left',
        'vertical-align': 'top',
        'border': '1px solid #ccc'
    })
    .set_table_styles([
        {'selector': 'th', 'props': [
            ('border', '1px solid #ccc'),
            ('background-color', '#f2f2f2'),
            ('font-weight', 'bold'),
            ('text-align', 'center')
        ]},
        {'selector': 'td', 'props': [
            ('border', '1px solid #ccc'),
            ('padding', '8px')
        ]}
    ])
    )
  return result
